/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 myroom.gltf 
*/

import { useGLTF, useTexture } from "@react-three/drei";
import React from "react";

import * as THREE from "three";
import { motion } from "framer-motion-3d";
import { useFrame } from "@react-three/fiber";
import { animate,useMotionValue } from "framer-motion";
import { useEffect } from "react";
export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF('models/myroom.gltf')
  const texture = useTexture("textures/baked.jpg");
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });
  const textureOpacity = useMotionValue(0);
  const glassTextureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0);
    animate(glassTextureOpacity, section === 0 ? 0.42 : 0);
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
    textureGlassMaterial.opacity = glassTextureOpacity.get();
  });
  return (
    <group {...props} dispose={null}>
      <group position={[2.353, -0.046, -1.135]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.922, 0]}>
            <group position={[-0.297, -0.038, -1.441]}>
              <mesh geometry={nodes.Object_85.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_87.geometry} material={materials['Material.007']} position={[-0.434, -0.84, 1.931]} rotation={[0, 0, -Math.PI / 2]} scale={[0.049, 0.017, 0.049]} />
            </group>
            <group position={[0, -0.159, 0.468]} scale={[0.172, 0.159, 0.172]}>
              <mesh geometry={nodes.Object_89.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_90.geometry} material={materials['Material.007']} />
            </group>
            <group position={[-0.343, 0.187, -1.422]} rotation={[Math.PI, -1.347, Math.PI / 2]} scale={[0.049, 0.92, 0.213]}>
              <mesh geometry={nodes.Object_92.geometry} material={materials['Material.006']} />
              <mesh geometry={nodes.Object_93.geometry} material={materials['Material.008']} />
            </group>
            <group position={[-0.723, -0.074, 0.842]} scale={0.012}>
              <mesh geometry={nodes.Object_9.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} position={[1.353, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_13.geometry} material={materials['Material.005']} position={[6.069, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_15.geometry} material={materials['Material.005']} position={[8.544, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_17.geometry} material={materials['Material.005']} position={[13.209, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_19.geometry} material={materials['Material.005']} position={[15.67, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_21.geometry} material={materials['Material.005']} position={[17.966, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_23.geometry} material={materials['Material.005']} position={[22.717, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_25.geometry} material={materials['Material.005']} position={[25.192, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_27.geometry} material={materials['Material.005']} position={[29.857, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_29.geometry} material={materials['Material.005']} position={[32.318, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_31.geometry} material={materials['Material.005']} position={[34.614, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_33.geometry} material={materials['Material.005']} position={[39.486, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_35.geometry} material={materials['Material.005']} position={[41.961, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_37.geometry} material={materials['Material.005']} position={[46.626, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_39.geometry} material={materials['Material.005']} position={[49.087, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_41.geometry} material={materials['Material.005']} position={[51.383, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_43.geometry} material={materials['Material.005']} position={[56.142, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_45.geometry} material={materials['Material.005']} position={[58.618, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_47.geometry} material={materials['Material.005']} position={[63.282, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_49.geometry} material={materials['Material.005']} position={[65.743, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_51.geometry} material={materials['Material.005']} position={[68.039, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_53.geometry} material={materials['Material.005']} position={[72.951, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_55.geometry} material={materials['Material.005']} position={[75.427, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_57.geometry} material={materials['Material.005']} position={[80.091, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_59.geometry} material={materials['Material.005']} position={[82.552, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_61.geometry} material={materials['Material.005']} position={[84.849, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_63.geometry} material={materials['Material.005']} position={[89.579, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_65.geometry} material={materials['Material.005']} position={[92.055, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_67.geometry} material={materials['Material.005']} position={[96.719, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_69.geometry} material={materials['Material.005']} position={[99.18, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_71.geometry} material={materials['Material.005']} position={[101.477, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_73.geometry} material={materials['Material.005']} position={[106.328, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_75.geometry} material={materials['Material.005']} position={[108.803, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_77.geometry} material={materials['Material.005']} position={[113.468, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_79.geometry} material={materials['Material.005']} position={[115.929, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_81.geometry} material={materials['Material.005']} position={[118.225, -0.007, -3.588]} scale={0.773} />
            </group>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} position={[-0.874, 0.307, 0.71]} rotation={[0, 0, 0.643]} />
            <mesh geometry={nodes.Object_83.geometry} material={materials['Material.001']} position={[0.718, 0.244, 0.118]} rotation={[0, 0, -0.914]} scale={0.055} />
          </group>
          <mesh geometry={nodes.Object_99.geometry} material={materials['Material.011']} position={[0, 0.509, 1.355]} scale={[0.429, 0.041, 0.27]} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.Material} position={[0, 0.509, 1.355]} scale={[0.429, 0.041, 0.27]} />
        </group>
      </group>
      <group position={[-0.074, 0, -1.521]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry}  material={textureMaterial} />
      </group>
      <group position={[-1.196, 2.386, -2.833]} scale={1.405}>
        <mesh geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={textureMaterial} />
      </group>
      <group
      name="LavaLamp"
      position={[-1.802, 2.876, -2.937]}>
        <mesh geometry={nodes['Node-Mesh001'].geometry}  material={textureMaterial} />
        <mesh geometry={nodes['Node-Mesh001_1'].geometry}  material={textureMaterial} />
        <mesh geometry={nodes['Node-Mesh001_2'].geometry}  material={textureMaterial} />
      </group>
      <mesh geometry={nodes.WawaRug.geometry}  material={textureMaterial} position={[-0.324, 0.03, 1.13]} scale={1.454} />
      <group position={[-1.265, 2.868, -2.914]} rotation={[-Math.PI, 0.728, -Math.PI]}>
        <mesh geometry={nodes.mesh434900071.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh434900071_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh434900071_2.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh434900071_3.geometry} material={textureMaterial}/>
        <mesh geometry={nodes.mesh434900071_4.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh434900071_5.geometry} material={textureMaterial}   />
      </group>
      <group name="keyboard" position={[-0.044, 0.981, -1.346]} rotation={[0, -0.165, 0]}>
        <mesh geometry={nodes.mesh425587018.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh425587018_1.geometry}  material={textureMaterial}/>
        <mesh geometry={nodes.mesh425587018_2.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh425587018_3.geometry}  material={textureMaterial} />
      </group>
      <group name="iMac" position={[0.454, 0.939, -1.723]} rotation={[Math.PI, -1.099, Math.PI]}>
        <mesh geometry={nodes.iMac_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.iMac_1_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.iMac_1_2.geometry}  material={textureMaterial} />
      </group>
      <mesh name="comp mouse" geometry={nodes.Comp_Mouse.geometry}  material={textureMaterial} />
      <group position={[-0.78, 1.071, -1.61]}>
        <mesh geometry={nodes.mesh24448074.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh24448074_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.mesh24448074_2.geometry}  material={textureMaterial} />
      </group>
      <group position={[-2.019, -0.042, -1.526]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Houseplant_7_1.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.Houseplant_7_2.geometry}  material={textureMaterial} />
        <mesh geometry={nodes.Houseplant_7_3.geometry} material={textureMaterial} />
      </group>
      <group name="chair" position={[-0.278, 0, -0.708]} rotation={[0, -0.376, 0]}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry}  material={textureMaterial} />
      </group>
      <group position={[-0.006, 0.031, 0]} scale={1.404}>
         <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_1"
        geometry={nodes.Plane001_1.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_2"
        geometry={nodes.Plane001_2.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_3"
        geometry={nodes.Plane001_3.geometry}
        material={textureGlassMaterial}
      />
      </group>
    </group>
  )
}

useGLTF.preload('models/myroom.gltf')
