/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 myroom.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/myroom.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[2.353, -0.046, -1.135]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.922, 0]}>
            <group position={[-0.297, -0.038, -1.441]}>
              <mesh geometry={nodes.Object_85.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_87.geometry} material={materials['Material.007']} position={[-0.434, -0.84, 1.931]} rotation={[0, 0, -Math.PI / 2]} scale={[0.049, 0.017, 0.049]} />
            </group>
            <group position={[0, -0.159, 0.468]} scale={[0.172, 0.159, 0.172]}>
              <mesh geometry={nodes.Object_89.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_90.geometry} material={materials['Material.007']} />
            </group>
            <group position={[-0.343, 0.187, -1.422]} rotation={[Math.PI, -1.347, Math.PI / 2]} scale={[0.049, 0.92, 0.213]}>
              <mesh geometry={nodes.Object_92.geometry} material={materials['Material.006']} />
              <mesh geometry={nodes.Object_93.geometry} material={materials['Material.008']} />
            </group>
            <group position={[-0.723, -0.074, 0.842]} scale={0.012}>
              <mesh geometry={nodes.Object_9.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} position={[1.353, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_13.geometry} material={materials['Material.005']} position={[6.069, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_15.geometry} material={materials['Material.005']} position={[8.544, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_17.geometry} material={materials['Material.005']} position={[13.209, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_19.geometry} material={materials['Material.005']} position={[15.67, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_21.geometry} material={materials['Material.005']} position={[17.966, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_23.geometry} material={materials['Material.005']} position={[22.717, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_25.geometry} material={materials['Material.005']} position={[25.192, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_27.geometry} material={materials['Material.005']} position={[29.857, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_29.geometry} material={materials['Material.005']} position={[32.318, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_31.geometry} material={materials['Material.005']} position={[34.614, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_33.geometry} material={materials['Material.005']} position={[39.486, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_35.geometry} material={materials['Material.005']} position={[41.961, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_37.geometry} material={materials['Material.005']} position={[46.626, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_39.geometry} material={materials['Material.005']} position={[49.087, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_41.geometry} material={materials['Material.005']} position={[51.383, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_43.geometry} material={materials['Material.005']} position={[56.142, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_45.geometry} material={materials['Material.005']} position={[58.618, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_47.geometry} material={materials['Material.005']} position={[63.282, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_49.geometry} material={materials['Material.005']} position={[65.743, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_51.geometry} material={materials['Material.005']} position={[68.039, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_53.geometry} material={materials['Material.005']} position={[72.951, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_55.geometry} material={materials['Material.005']} position={[75.427, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_57.geometry} material={materials['Material.005']} position={[80.091, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_59.geometry} material={materials['Material.005']} position={[82.552, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_61.geometry} material={materials['Material.005']} position={[84.849, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_63.geometry} material={materials['Material.005']} position={[89.579, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_65.geometry} material={materials['Material.005']} position={[92.055, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_67.geometry} material={materials['Material.005']} position={[96.719, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_69.geometry} material={materials['Material.005']} position={[99.18, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_71.geometry} material={materials['Material.005']} position={[101.477, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_73.geometry} material={materials['Material.005']} position={[106.328, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_75.geometry} material={materials['Material.005']} position={[108.803, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_77.geometry} material={materials['Material.005']} position={[113.468, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_79.geometry} material={materials['Material.005']} position={[115.929, -0.007, -3.588]} scale={0.773} />
              <mesh geometry={nodes.Object_81.geometry} material={materials['Material.005']} position={[118.225, -0.007, -3.588]} scale={0.773} />
            </group>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} position={[-0.874, 0.307, 0.71]} rotation={[0, 0, 0.643]} />
            <mesh geometry={nodes.Object_83.geometry} material={materials['Material.001']} position={[0.718, 0.244, 0.118]} rotation={[0, 0, -0.914]} scale={0.055} />
          </group>
          <mesh geometry={nodes.Object_99.geometry} material={materials['Material.011']} position={[0, 0.509, 1.355]} scale={[0.429, 0.041, 0.27]} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.Material} position={[0, 0.509, 1.355]} scale={[0.429, 0.041, 0.27]} />
        </group>
      </group>
      <group position={[-0.074, 0, -1.521]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={materials['BlackWood.001']} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={materials['GrayPlastic.001']} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={materials['WhiteSteelScrew.001']} />
        <mesh geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={materials['BlackPlastic.001']} />
      </group>
      <group position={[-1.196, 2.356, -2.833]} scale={1.305}>
        <mesh geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials['795548.001']} />
      </group>
      <group position={[-1.802, 2.876, -2.937]}>
        <mesh geometry={nodes['Node-Mesh001'].geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes['Node-Mesh001_1'].geometry} material={materials['lambert2SG.001']} />
        <mesh geometry={nodes['Node-Mesh001_2'].geometry} material={materials['lambert3SG.002']} />
      </group>
      <mesh geometry={nodes.WawaRug.geometry} material={materials.Rug} position={[-0.324, 0.03, 0.98]} scale={1.154} />
      <group position={[-1.265, 2.868, -2.914]} rotation={[-Math.PI, 0.728, -Math.PI]}>
        <mesh geometry={nodes.mesh434900071.geometry} material={materials.mat14} />
        <mesh geometry={nodes.mesh434900071_1.geometry} material={materials.mat13} />
        <mesh geometry={nodes.mesh434900071_2.geometry} material={materials['mat12.001']} />
        <mesh geometry={nodes.mesh434900071_3.geometry} material={materials['mat21.003']} />
        <mesh geometry={nodes.mesh434900071_4.geometry} material={materials['mat23.001']} />
        <mesh geometry={nodes.mesh434900071_5.geometry} material={materials.mat11} />
      </group>
      <group position={[-0.044, 0.981, -1.346]} rotation={[0, -0.165, 0]}>
        <mesh geometry={nodes.mesh425587018.geometry} material={materials['mat21.004']} />
        <mesh geometry={nodes.mesh425587018_1.geometry} material={materials['mat22.001']} />
        <mesh geometry={nodes.mesh425587018_2.geometry} material={materials['mat9.002']} />
        <mesh geometry={nodes.mesh425587018_3.geometry} material={materials['mat16.001']} />
      </group>
      <group position={[0.454, 0.939, -1.723]} rotation={[Math.PI, -1.099, Math.PI]}>
        <mesh geometry={nodes.iMac_1.geometry} material={materials.Screen} />
        <mesh geometry={nodes.iMac_1_1.geometry} material={materials.ScreenBlack} />
        <mesh geometry={nodes.iMac_1_2.geometry} material={materials.iMacBody} />
      </group>
      <mesh geometry={nodes.Comp_Mouse.geometry} material={materials['lambert3SG.003']} />
      <group position={[-0.78, 1.071, -1.61]}>
        <mesh geometry={nodes.mesh24448074.geometry} material={materials['mat9.003']} />
        <mesh geometry={nodes.mesh24448074_1.geometry} material={materials['mat20.001']} />
        <mesh geometry={nodes.mesh24448074_2.geometry} material={materials['mat21.005']} />
      </group>
      <group position={[-2.019, -0.042, -1.526]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Houseplant_7_1.geometry} material={materials['Black.001']} />
        <mesh geometry={nodes.Houseplant_7_2.geometry} material={materials['Brown.001']} />
        <mesh geometry={nodes.Houseplant_7_3.geometry} material={materials['Plant_Green.001']} />
      </group>
      <group position={[-0.278, 0, -0.708]} rotation={[0, -0.376, 0]}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
      </group>
      <group position={[-0.006, 0.031, 0]} scale={1.404}>
        <mesh geometry={nodes.Plane001.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials.Wall} />
        <mesh geometry={nodes.Plane001_4.geometry} material={materials.Glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/myroom.gltf')
